# Generated by Django 3.1.3 on 2020-11-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-id'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-id'], 'verbose_name': 'record'},
        ),
    ]
