# Generated by Django 3.1.4 on 2020-12-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='record',
            name='activities',
        ),
        migrations.AddField(
            model_name='record',
            name='activities',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.activity'),
        ),
    ]
