# Generated by Django 3.1.4 on 2020-12-22 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
