# Generated by Django 3.1.4 on 2020-12-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201208_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='activities',
            new_name='activity',
        ),
    ]
