# Generated by Django 3.1.4 on 2021-01-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201222_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='timeline',
            new_name='timelineID',
        ),
    ]
