# Generated by Django 3.1.4 on 2021-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
